CREATE TABLE USERS(
  ID NUMBER,
  CONSTRAINT USERS_PK PRIMARY KEY(ID),
  FIRST_NAME NVARCHAR2(40),
  LAST_NAME NVARCHAR2(60),
  PHONE NVARCHAR2(20),
  COUNTRY NVARCHAR2(40),
  CITY NVARCHAR2(60),
  AGE NUMBER,
  DATE_REGISTERED TIMESTAMP,
  DATE_LAST_ACTIVE TIMESTAMP,
  RELATIONSHIP_STATUS NVARCHAR2(40),
  RELIGION NVARCHAR2(50),
  SCHOOL NVARCHAR2(200),
  UNIVERSITY NVARCHAR2(200)
);

DROP TABLE USERS;