CREATE TABLE POSTS(
  POST_ID NUMBER,
  CONSTRAINT POST_PK PRIMARY KEY(POST_ID),
  MESSAGE NVARCHAR2(500),
  DATE_POSTED TIMESTAMP,
  USER_POSTED_ID NUMBER,
  CONSTRAINT USER_POSTED_FK FOREIGN KEY(USER_POSTED_ID) REFERENCES USERS(USER_ID)
);