CREATE TABLE RELATIONSHIPS (
  USER_FROM_ID NUMBER,
  CONSTRAINT RELATIONSHIP_USER_FROM_FK FOREIGN KEY (USER_FROM_ID) REFERENCES USERS (ID),
  USER_TO_ID   NUMBER,
  CONSTRAINT RELATIONSHIP_USER_TO_FK FOREIGN KEY (USER_TO_ID) REFERENCES USERS (ID),
  STATUS       NVARCHAR2(50) NOT NULL
);